version: "3.9"

services:
  # https://github.com/FlorianLeChat/GmodStore-Downloader
  php-nginx:
    image: gmodstoredownloader
    container_name: website
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80