name: gmodstore-downloader

version: "3.8"

services:
    # https://github.com/FlorianLeChat/GmodStore-Downloader
    php:
        image: gmodstore-downloader
        restart: always
        develop:
            watch:
                - action: sync
                  path: .
                  target: /var/www/html
        healthcheck:
            test: curl -f http://127.0.0.1:9000/ 2>&1 | grep "Connection reset by peer" || curl -f http://localhost
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
        ports:
            - "80:80"